version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017

configuration: Release

platform: Any CPU
assembly_info:
  patch: true
  file: 'nkxtract\Properties\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}.0'

#install:
#- cmd: git submodule update --init --recursive

#before_build:
#- cmd: nuget restore nkxtract.sln

build:
  project: nkxtract.sln
  parallel: true
  verbosity: minimal

after_build:
 - >
   7z a nkxtract-%APPVEYOR_BUILD_VERSION%.zip 
   %APPVEYOR_BUILD_FOLDER%\nkxtract\bin\Release\nkxtract.exe
   %APPVEYOR_BUILD_FOLDER%\README.md
   %APPVEYOR_BUILD_FOLDER%\COPYING

artifacts:
- path: nkxtract-%APPVEYOR_BUILD_VERSION%.zip 