name: Build nkxtract

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 4.5
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -o output
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - uses: actions/upload-artifact@v3
      with:
        name: nkxtract
        path: output/nkxtract.exe
